import { User, Project, Column, Task, RFI, Attachment, Comment, RFIHistory } from './types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: '陳建勳 (Alex Chen)',
    email: 'alex.chen@pms-corp.com',
    role: 'SUPER_ADMIN',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    title: '首席架構工程師',
    department: '研發技術處'
  },
  {
    id: 'usr-pm-1',
    name: '林雅晴 (Claire Lin)',
    email: 'claire.lin@pms-corp.com',
    role: 'PM',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    title: '資深工程專案經理 (PMP)',
    department: '專案管理辦公室 (PMO)'
  },
  {
    id: 'usr-eng-1',
    name: '張晉瑋 (David Chang)',
    email: 'david.chang@pms-corp.com',
    role: 'MEMBER',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    title: 'BIM 結構工程專案組長',
    department: '土木機電工程部'
  },
  {
    id: 'usr-eng-2',
    name: '黃郁婷 (Eva Huang)',
    email: 'eva.huang@pms-corp.com',
    role: 'MEMBER',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    title: '機電與自控系統工程師',
    department: '智慧樓宇整合小組'
  },
  {
    id: 'usr-guest-1',
    name: '吳國華 (Ken Wu)',
    email: 'ken.wu@client-auditor.org',
    role: 'GUEST_AUDITOR',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    title: '業主委任第三方查核技師',
    department: '外部審查小組 (Auditor)'
  }
];

export const INITIAL_PROJECT: Project = {
  id: 'proj-bld1',
  code: 'BLD1',
  name: '高鐵科技新站區機電與 IoT 智慧監控整合專案 (Phase 2)',
  description: '涵蓋地下 2 層至地上 8 層智慧能源調控、BIM 管線碰撞排解、防火自動排煙聯鎖與感測系統工程。',
  startDate: '2026-03-01',
  targetEndDate: '2026-12-31',
  status: 'ACTIVE'
};

export const INITIAL_COLUMNS: Column[] = [
  { id: 'col-backlog', boardId: 'board-main', title: '待處理 (Backlog)', color: '#64748b', position: 1000 },
  { id: 'col-inprogress', boardId: 'board-main', title: '進行中 (In Progress)', color: '#2563eb', position: 2000 },
  { id: 'col-review', boardId: 'board-main', title: '待審查 (Under Review)', color: '#d97706', position: 3000 },
  { id: 'col-done', boardId: 'board-main', title: '已完成 (Done)', color: '#059669', position: 4000 }
];

export const INITIAL_ATTACHMENTS: Attachment[] = [
  {
    id: 'att-1',
    entityType: 'TASK',
    entityId: 'task-1',
    fileName: 'B2_BIM_Collision_Report_v2.dwg',
    fileSize: 14250000, // ~14.2 MB
    mimeType: 'application/acad',
    storageKey: 'bld1/tasks/task-1/B2_BIM_Collision_Report_v2.dwg',
    fileUrl: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=1000&auto=format&fit=crop&q=80',
    uploaderId: 'usr-eng-1',
    uploaderName: '張晉瑋 (David Chang)',
    createdAt: '2026-09-08T09:30:00Z'
  },
  {
    id: 'att-2',
    entityType: 'TASK',
    entityId: 'task-2',
    fileName: 'Site_Inspection_Switchboard_0905.jpg',
    fileSize: 3420000, // ~3.4 MB
    mimeType: 'image/jpeg',
    storageKey: 'bld1/tasks/task-2/Site_Inspection_Switchboard_0905.jpg',
    fileUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=1000&auto=format&fit=crop&q=80',
    uploaderId: 'usr-eng-2',
    uploaderName: '黃郁婷 (Eva Huang)',
    createdAt: '2026-09-09T14:15:00Z'
  },
  {
    id: 'att-3',
    entityType: 'RFI',
    entityId: 'rfi-1',
    fileName: 'HVAC_Duct_Conflict_Diagram.png',
    fileSize: 2150000,
    mimeType: 'image/png',
    storageKey: 'bld1/rfis/rfi-1/HVAC_Duct_Conflict_Diagram.png',
    fileUrl: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=1000&auto=format&fit=crop&q=80',
    uploaderId: 'usr-eng-1',
    uploaderName: '張晉瑋 (David Chang)',
    createdAt: '2026-09-07T11:00:00Z'
  }
];

export const INITIAL_RFIS: RFI[] = [
  {
    id: 'rfi-1',
    rfiCode: 'RFI-BLD1-2026-0041',
    projectId: 'proj-bld1',
    subject: 'B2F 冰水主機房風管與主要樑柱結構穿越淨高衝突疑義',
    question: `現場放樣發現依原建築圖 MEP-204 與結構施作圖 STR-108，B2 冰水主機專用空調回風主風管 (尺寸 1800x600mm) 與 3 號主承重樑下緣衝突，淨高僅剩 1.85 公尺，未符法規要求之 2.1 公尺以上維護通行高度。
    
請釐清是否得改採側向分流雙風管 (800x500mm x2) 繞行穿越，或須進行樑柱局部結構加強後開孔穿樑。`,
    suggestedSolution: '建議改採 2 支並聯扁平風管 (800x500mm)，於 3-4 跨間穿過次樑間隙，可保留淨高 2.25m 且不更動主樑配筋。',
    officialResponse: '經結構顧問與電機技師覆核，同意採「並聯扁平風管側繞」方案。請結構技師出具加勁鐵板固定細部圖並於三日內提送送審。',
    status: 'ANSWERED',
    costImpact: true,
    costAmount: 120000,
    scheduleImpact: 3,
    assignedTo: 'usr-pm-1',
    requestedBy: 'usr-eng-1',
    dueDate: '2026-09-12',
    relatedTaskIds: ['task-1'],
    createdAt: '2026-09-07T10:45:00Z',
    updatedAt: '2026-09-09T16:20:00Z',
    clientSigned: true,
    pmSigned: true
  },
  {
    id: 'rfi-2',
    rfiCode: 'RFI-BLD1-2026-0042',
    projectId: 'proj-bld1',
    subject: '3F 旅客大廳 IoT 光纖幹線協定與防火區劃穿壁密封件規格變更',
    question: `大廳 IoT 廣播與動態疏散顯示器原設計採 Cat.6A STP 訊號線，業主近期要求未來支援 10G 頻寬改為 OM4 多模多芯光纖。
    
穿過 2 小時防火區劃時，原發泡防火泥填塞材需更換為通過 UL1479 認證之預製型彈性防火套管模組，請核定材料規格清單。`,
    suggestedSolution: '提送 Hilti CFS-BL / Roxtec R 型防火穿透密封套模組規格書，並檢附 2hr 防火時效測試合格證明。',
    officialResponse: '',
    status: 'IN_REVIEW',
    costImpact: true,
    costAmount: 285000,
    scheduleImpact: 5,
    assignedTo: 'usr-guest-1',
    requestedBy: 'usr-eng-2',
    dueDate: '2026-09-15',
    relatedTaskIds: ['task-3'],
    createdAt: '2026-09-09T08:30:00Z',
    updatedAt: '2026-09-09T10:00:00Z',
    clientSigned: false,
    pmSigned: true
  },
  {
    id: 'rfi-3',
    rfiCode: 'RFI-BLD1-2026-0043',
    projectId: 'proj-bld1',
    subject: '月台層緊急發電機自動併聯測試排程與台電供電窗口會勘',
    question: '緊急發電機 1500kVA ATS 自動切換開關與市電饋線連動之併聯無停電負載試驗，需台電維護班到場掛錶會勘，需專案經理協助公文函文台電調度中心。',
    suggestedSolution: '於 2026-09-20 深夜 01:00-04:00 離峰時間進行停電測試作業。',
    officialResponse: '',
    status: 'SUBMITTED',
    costImpact: false,
    costAmount: 0,
    scheduleImpact: 0,
    assignedTo: 'usr-pm-1',
    requestedBy: 'usr-eng-2',
    dueDate: '2026-09-18',
    relatedTaskIds: ['task-4'],
    createdAt: '2026-09-10T14:00:00Z',
    updatedAt: '2026-09-10T14:00:00Z',
    clientSigned: false,
    pmSigned: false
  }
];

export const INITIAL_RFI_HISTORIES: RFIHistory[] = [
  {
    id: 'hist-1',
    rfiId: 'rfi-1',
    actorId: 'usr-eng-1',
    actorName: '張晉瑋 (David Chang)',
    action: '提出資訊請求單 (Submit RFI)',
    fromStatus: 'DRAFT',
    toStatus: 'SUBMITTED',
    note: '發現 B2 冰水主機房與 STR-108 樑柱衝突問題，上傳現場相片及 CAD 模擬圖',
    timestamp: '2026-09-07T10:45:00Z'
  },
  {
    id: 'hist-2',
    rfiId: 'rfi-1',
    actorId: 'usr-pm-1',
    actorName: '林雅晴 (Claire Lin)',
    action: '指派審查與進展至處理中 (In Review)',
    fromStatus: 'SUBMITTED',
    toStatus: 'IN_REVIEW',
    note: '已轉交電機技師與結構工程技師進行並聯扁平風管承重模擬',
    timestamp: '2026-09-08T09:10:00Z'
  },
  {
    id: 'hist-3',
    rfiId: 'rfi-1',
    actorId: 'usr-pm-1',
    actorName: '林雅晴 (Claire Lin)',
    action: '提供官方正式答覆 (Official Response)',
    fromStatus: 'IN_REVIEW',
    toStatus: 'ANSWERED',
    note: '同意採雙風管側繞方案，估計工期影響 3 天，追加成本 $120,000 元',
    timestamp: '2026-09-09T16:20:00Z'
  }
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 'phase-1',
    projectId: 'proj-bld1',
    columnId: 'col-inprogress',
    wpType: 'PHASE',
    title: 'B2F 機電與重電主系統工程整合驗收',
    description: '包含消防撒水試驗、冰水機房 BIM 碰撞排解、柴油發電機排氣降噪檢驗。',
    priority: 'URGENT',
    startDate: '2026-09-01',
    dueDate: '2026-09-16',
    progress: 80,
    dependencies: [],
    isMilestone: false,
    milestone: 'M1: B2F 結構與重電驗收',
    position: 100,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-pm-1',
    collaboratorIds: ['usr-eng-1', 'usr-eng-2'],
    tags: ['工程階段', 'B2F機電', '主階段'],
    moduleName: '工程總排程',
    relatedRfiIds: [],
    createdAt: '2026-08-30T08:00:00Z',
    updatedAt: '2026-09-10T12:00:00Z'
  },
  {
    id: 'task-5',
    projectId: 'proj-bld1',
    columnId: 'col-done',
    wpType: 'TASK',
    parentId: 'phase-1',
    title: '1F-4F 消防自動撒水系統管線水壓耐壓試驗 (14 kgf/cm²)',
    description: `已完成連續 2 小時 14 kgf/cm² 加壓試驗，壓力降值為 0 kgf/cm²，符合規範要求。
現場主管與消防技師均已於驗收單正本完成用印。`,
    priority: 'MEDIUM',
    startDate: '2026-09-01',
    dueDate: '2026-09-06',
    progress: 100,
    dependencies: [],
    isMilestone: false,
    milestone: 'M1: B2F 結構與重電驗收',
    position: 500,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-eng-1',
    collaboratorIds: ['usr-pm-1'],
    tags: ['消防驗收', '耐壓測試', '已結案'],
    moduleName: '消防工程',
    relatedRfiIds: [],
    createdAt: '2026-09-01T09:00:00Z',
    updatedAt: '2026-09-06T17:30:00Z'
  },
  {
    id: 'task-1',
    projectId: 'proj-bld1',
    columnId: 'col-inprogress',
    wpType: 'TASK',
    parentId: 'phase-1',
    title: 'B2 冰水機房 3D BIM 管線碰撞檢核與迴避工法送審',
    description: `### 工項重點
1. 針對現場 3 號柱與冰水回風管衝突建立 Navisworks 碰撞檢測。
2. 配合 **RFI-BLD1-2026-0041** 決議，繪製並聯扁平風管 (800x500mm x2) 施工圖。
3. 安排與結構技師確認吊架防震拉桿固定間距 (符合抗震 0.4g 規範)。

![B2現場檢核圖](https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=800&auto=format&fit=crop&q=80)
`,
    priority: 'URGENT',
    startDate: '2026-09-06',
    dueDate: '2026-09-14',
    progress: 65,
    dependencies: ['task-5'],
    isMilestone: false,
    milestone: 'M1: B2F 結構與重電驗收',
    position: 1000,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-eng-1',
    collaboratorIds: ['usr-eng-2', 'usr-pm-1'],
    tags: ['BIM', '機電衝突', '結構安全', 'Critical'],
    moduleName: '地下機電工程',
    relatedRfiIds: ['rfi-1'],
    createdAt: '2026-09-05T08:00:00Z',
    updatedAt: '2026-09-09T14:00:00Z'
  },
  {
    id: 'task-4',
    projectId: 'proj-bld1',
    columnId: 'col-review',
    wpType: 'TASK',
    parentId: 'phase-1',
    title: '1500kVA 緊急柴油發電機排氣系統消音器降噪量測',
    description: `量測發電機滿載 (100% Load Bank) 運轉時，站體周界噪音是否小於 65 dBA。
目前完成初測，量測數據 63.8 dBA 符合環保署法規要求，等待第三方查核技師 @吳國華 簽署檢驗證明單。`,
    priority: 'HIGH',
    startDate: '2026-09-08',
    dueDate: '2026-09-16',
    progress: 85,
    dependencies: ['task-1'],
    isMilestone: false,
    milestone: 'M1: B2F 結構與重電驗收',
    position: 1500,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-eng-2',
    collaboratorIds: ['usr-guest-1', 'usr-pm-1'],
    tags: ['柴油發電機', '噪音檢測', '第三方驗收'],
    moduleName: '重電設施模組',
    relatedRfiIds: ['rfi-3'],
    createdAt: '2026-09-04T13:00:00Z',
    updatedAt: '2026-09-10T12:15:00Z'
  },
  {
    id: 'task-m1',
    projectId: 'proj-bld1',
    columnId: 'col-review',
    wpType: 'MILESTONE',
    title: '里程碑 M1：B2F 重電設備與主要管線查核完成點交',
    description: 'B2F 變電機房、耐壓測試與冰水主機迴避施工全面完成第三方工程抽查。',
    priority: 'URGENT',
    startDate: '2026-09-16',
    dueDate: '2026-09-16',
    progress: 80,
    dependencies: ['phase-1'],
    isMilestone: true,
    milestone: 'M1: B2F 結構與重電驗收',
    position: 2000,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-pm-1',
    collaboratorIds: ['usr-guest-1'],
    tags: ['Milestone', '業主初檢', '里程碑'],
    moduleName: '專案管制里程碑',
    relatedRfiIds: ['rfi-1'],
    createdAt: '2026-09-02T08:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z'
  },
  {
    id: 'phase-2',
    projectId: 'proj-bld1',
    columnId: 'col-inprogress',
    wpType: 'PHASE',
    title: '智慧變電站併網與 SCADA 弱電系統測試',
    description: '涵蓋 SCADA PLC 通訊線路查線、智慧電錶定址與防火套管檢驗提送。',
    priority: 'HIGH',
    startDate: '2026-09-10',
    dueDate: '2026-09-24',
    progress: 35,
    dependencies: ['task-m1'],
    isMilestone: false,
    milestone: 'M2: 智慧變電站併網',
    position: 2500,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-pm-1',
    collaboratorIds: ['usr-eng-2'],
    tags: ['工程階段', 'SCADA', '弱電工程'],
    moduleName: '工程總排程',
    relatedRfiIds: [],
    createdAt: '2026-09-04T08:00:00Z',
    updatedAt: '2026-09-10T09:00:00Z'
  },
  {
    id: 'task-2',
    projectId: 'proj-bld1',
    columnId: 'col-inprogress',
    wpType: 'TASK',
    parentId: 'phase-2',
    title: '智慧變電站 SCADA 訊號點測試與 PLC 閘道器韌體刷寫',
    description: `### 施作內容
- 對接西門子 S7-1500 PLC 與 Modbus TCP/IP 閘道。
- 檢驗 128 組比流器 (CT)、比壓器 (PT) 與斷路器輔助接點狀態。
- 記錄目前連線狀態回傳延遲 (< 150ms 達標)。`,
    priority: 'HIGH',
    startDate: '2026-09-10',
    dueDate: '2026-09-18',
    progress: 45,
    dependencies: [],
    isMilestone: false,
    milestone: 'M2: 智慧變電站併網',
    position: 3000,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-eng-2',
    collaboratorIds: ['usr-admin-1'],
    tags: ['SCADA', 'PLC', '自動化', 'IoT'],
    moduleName: '電力監控模組',
    relatedRfiIds: [],
    createdAt: '2026-09-06T10:00:00Z',
    updatedAt: '2026-09-08T11:20:00Z'
  },
  {
    id: 'task-3',
    projectId: 'proj-bld1',
    columnId: 'col-backlog',
    wpType: 'TASK',
    parentId: 'phase-2',
    title: '3F 大廳 10G 光纖穿壁 UL 防火密封模組工料送審',
    description: `針對大廳疏散顯示器線路升級，提送 Roxtec 防火套管材料樣品與檢驗報告。
請配合 **RFI-BLD1-2026-0042** 審查回覆辦理。`,
    priority: 'MEDIUM',
    startDate: '2026-09-14',
    dueDate: '2026-09-24',
    progress: 15,
    dependencies: ['task-2'],
    isMilestone: false,
    milestone: 'M3: 智慧弱電工程',
    position: 3500,
    createdBy: 'usr-eng-2',
    assigneeId: 'usr-eng-2',
    collaboratorIds: ['usr-guest-1'],
    tags: ['弱電光纖', '防火區劃', '送審'],
    moduleName: '大廳弱電工程',
    relatedRfiIds: ['rfi-2'],
    createdAt: '2026-09-09T08:45:00Z',
    updatedAt: '2026-09-09T08:45:00Z'
  },
  {
    id: 'task-m2',
    projectId: 'proj-bld1',
    columnId: 'col-backlog',
    wpType: 'MILESTONE',
    title: '里程碑 M2：智慧變電站併網通電測試點交',
    description: '完成 SCADA 訊號雙向閉迴路檢核，通過台電併聯通電安全檢查。',
    priority: 'URGENT',
    startDate: '2026-09-25',
    dueDate: '2026-09-25',
    progress: 0,
    dependencies: ['phase-2'],
    isMilestone: true,
    milestone: 'M2: 智慧變電站併網',
    position: 3800,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-pm-1',
    collaboratorIds: ['usr-eng-2'],
    tags: ['Milestone', '併網測試', '里程碑'],
    moduleName: '專案管制里程碑',
    relatedRfiIds: [],
    createdAt: '2026-09-08T08:00:00Z',
    updatedAt: '2026-09-10T11:00:00Z'
  },
  {
    id: 'phase-3',
    projectId: 'proj-bld1',
    columnId: 'col-backlog',
    wpType: 'PHASE',
    title: '智慧月台感測安裝與雙迴路自動切換 (ATS) 試車',
    description: '光達支撐機構架加工與全區緊急備援電源切換驗證。',
    priority: 'HIGH',
    startDate: '2026-09-22',
    dueDate: '2026-10-04',
    progress: 0,
    dependencies: ['task-m2'],
    isMilestone: false,
    milestone: 'M4: 智慧月台感測',
    position: 4000,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-eng-1',
    collaboratorIds: ['usr-eng-2'],
    tags: ['工程階段', '月台感測', 'ATS試車'],
    moduleName: '工程總排程',
    relatedRfiIds: [],
    createdAt: '2026-09-08T09:00:00Z',
    updatedAt: '2026-09-10T09:00:00Z'
  },
  {
    id: 'task-6',
    projectId: 'proj-bld1',
    columnId: 'col-backlog',
    wpType: 'TASK',
    parentId: 'phase-3',
    title: '智慧月台防夾感應光達 (LiDAR) 安裝腳架結構加固圖發包',
    description: `需發包金屬加工廠製造 SUS304 懸臂支撐架，並安排於夜間天窗時段 (01:30 - 04:30) 進行站台面開孔錨定。`,
    priority: 'LOW',
    startDate: '2026-09-22',
    dueDate: '2026-09-30',
    progress: 0,
    dependencies: [],
    isMilestone: false,
    milestone: 'M4: 智慧月台感測',
    position: 4200,
    createdBy: 'usr-eng-1',
    assigneeId: 'usr-eng-1',
    collaboratorIds: [],
    tags: ['光達LiDAR', '機構件', '夜間作業'],
    moduleName: '月台感測工程',
    relatedRfiIds: [],
    createdAt: '2026-09-10T09:00:00Z',
    updatedAt: '2026-09-10T09:00:00Z'
  },
  {
    id: 'task-7',
    projectId: 'proj-bld1',
    columnId: 'col-backlog',
    wpType: 'TASK',
    parentId: 'phase-3',
    title: '全區高低壓雙迴路送電並聯試車與自動切換 (ATS) 驗證',
    description: '模擬台電主迴路斷電，柴油發電機在 10 秒內自啟動並經由 ATS 盤向第一類緊急負載供電。',
    priority: 'URGENT',
    startDate: '2026-09-26',
    dueDate: '2026-10-04',
    progress: 0,
    dependencies: ['task-6'],
    isMilestone: false,
    milestone: 'M2: 智慧變電站併網',
    position: 4500,
    createdBy: 'usr-pm-1',
    assigneeId: 'usr-eng-2',
    collaboratorIds: ['usr-eng-1', 'usr-guest-1'],
    tags: ['ATS測試', '緊急備援', '試車'],
    moduleName: '電力監控模組',
    relatedRfiIds: [],
    createdAt: '2026-09-10T10:30:00Z',
    updatedAt: '2026-09-10T10:30:00Z'
  }
];

export const INITIAL_COMMENTS: Comment[] = [
  {
    id: 'comm-1',
    taskId: 'task-1',
    authorId: 'usr-pm-1',
    authorName: '林雅晴 (Claire Lin)',
    authorAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    content: '請 @張晉瑋 特別留意樑下錨定深度不得傷及預力鋼絞線，並請先參考 RFI-BLD1-2026-0041 的正式答覆方案！',
    mentions: ['usr-eng-1'],
    createdAt: '2026-09-09T17:00:00Z'
  },
  {
    id: 'comm-2',
    taskId: 'task-1',
    authorId: 'usr-eng-1',
    authorName: '張晉瑋 (David Chang)',
    authorAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    content: '收到，已透過透地雷達 (GPR) 完成鋼筋與鋼絞線深層掃描，預留 120mm 安全邊界，明天下午出圖。',
    mentions: ['usr-pm-1'],
    createdAt: '2026-09-09T18:15:00Z'
  }
];
